### ISSUE TITLE
How about 'openface_server.lua'

### ISSUE THREAD

**Issue by Jacktofine** [thnkim/OpenFacePytorch#1]
Hello, thnkim!
      The code of openface for pytorch is help me. I am trying to run it but didn't work at last step, it's the problem of the file of 'openface_server.lua'.I'm not family with Torch and appreciate you can transform this file to pytorch !

**Comment by thnkim** [comment]
Hello, so sorry for the belated response.
It looks openface_server.lua is a code for serving OpenFace in torch.
If you would like to run my code in pytorch, there is a sample code (although it is not clean). 
If you need a server that openface_server.lua does, well.. it is not the scope of this (openFacePytorch).
