### ISSUE TITLE
How to run your codes with multiple GPU?

### ISSUE THREAD

**Issue by bluer555** [thnkim/OpenFacePytorch#2]
Hi, thnkim!

I'm using your codes to fine tune our face recognition network in pytorch, it works well when using single GPU (gpuDevice=0), I want to know how to run it with multiple GPU?

thanks!

**Comment by thnkim** [comment]
Hello, sorry for the belated response.

When you call prepareOpenFace(), you can set ```useMultiGPU=True```, then it should use pyTorch's nn.DataParallel(). If you would like to use some specific GPU device(s), you can modify the line ```model = nn.DataParallel(model)``` below.  

```
def prepareOpenFace(useCuda=True, gpuDevice=0, useMultiGPU=False):
    model = netOpenFace(useCuda, gpuDevice)
    model.load_state_dict(torch.load(os.path.join(containing_dir, 'openface.pth')))

    if useMultiGPU:
        model = nn.DataParallel(model)

    return model
```


But, I guess you've already tried this. Did you have an issue that I am not aware?
