### ISSUE TITLE
Is input size (batchseize,3,96,96) right?

### ISSUE THREAD

**Issue by SuperFreeMan-CXM** [thnkim/OpenFacePytorch#6]
When I'm trying outputs_128, outputs_726 = face_net(imgs_tensor) (imgs_tensor is [3,3,96,96]) , I got an error :
ValueError: Expected more than 1 value per channel when training, got input size [1, 96, 1, 1].
can you solve that?

**Comment by thnkim** [comment]
Hello, at which line did you get the error?

**Comment by SuperFreeMan-CXM** [comment]
Hello，thank you for your reply, I have solved the above problem.
Since we can get a vector(128d) from a picture，I used the L2 norm to calculate the difference between the two pictures，but I found no difference in the L2 norm between different people and the same people。
For example:
Pictures of myself is 1.91（L2 norm）
Pictures between me and someone else is 1.92 (L2 norm)
It looks like this model is not trained.
I would appreciate it if you could give me some advice

**Comment by educob** [comment]
Thanks for the code. I have learned a lot.

But when I run the example I got that lennon with glasses was closer to clapton with glasses than to lennon without glasses.
I think this is completely wrong.
Thanks.
